apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hp-app
  template:
    metadata:
      labels:
        app: hp-app
    spec:
      containers:
        - name: hp-app
          image: 192.168.1.10:8443/hp-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:oracle:thin:@192.168.1.102:31521:xe
            - name: SPRING_DATASOURCE_USERNAME
              value: HEALTH
            - name: SPRING_DATASOURCE_PASSWORD
              value: HEALTH
          volumeMounts:
            - name: nfs-volume
              mountPath: /opt/upload
      volumes:
        - name: nfs-volume
          nfs:
            server: 192.168.1.10
            path: /nfs_shared/spring/upload
