version: '3'
services:
  spring:
    container_name: hp-app
    image: localhost:8443/hp-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@172.26.254.26:1521:xe"
      SPRING_DATASOURCE_USERNAME: "HEALTH"
      SPRING_DATASOURCE_PASSWORD: "HEALTH"
    volumes:
      - /nfs_shared/spring/upload:/opt/upload
    restart: always
